# Generated by Django 4.2.1 on 2023-05-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="destination",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
